<?php
$SQL_HOST = "SQL_HOST";
$SQL_PORT = "SQL_PORT";
$SQL_USERNAME = "SQL_USERNAME";
$SQL_PASSWORD = "SQL_PASSWORD";
$SQL_DATABASE = "SQL_PASSWORD";
$MEMCACHE_HOST = "MEMCACHE_HOST";
$MEMCACHE_PORT = "MEMCACHE_PORT";
?>