<?php
define("SQL_HOST", "SQL_HOST");
define("SQL_PORT", "SQL_PORT");
define("SQL_USERNAME", "SQL_USERNAME");
define("SQL_PASSWORD", "SQL_PASSWORD");
define("SQL_DATABASE", "SQL_DATABASE");
define("MEMCACHE_HOST", "MEMCACHE_HOST");
define("MEMCACHE_PORT", "MEMCACHE_PORT");
define("MEMCACHE_TIME", "MEMCACHE_TIME");
$config = array(SQL_HOST => "localhost", SQL_PORT => 3306, SQL_USERNAME => "root", SQL_PASSWORD => "", SQL_DATABASE => "nineoneporn", MEMCACHE_HOST => "127.0.0.1", MEMCACHE_PORT => 11211, MEMCACHE_TIME => 3600);
?>